version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./conf/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - myweb

  myweb:
    image: myweb:latest
    build: .
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    tty: true #up启动后不会立刻退出exit, 但无法使用docker attach
    # command: ./dev_start.sh #bash -c "python django1/manage.py runserver 0.0.0.0:8000 > django.log 2>&1"
    depends_on:
      - mysql
      - redis
  
  mysql:
    image: mysql:8.0.28-oracle
    volumes:
      - ./datadir/mysql:/var/lib/mysql #挂到宿主机
      - ./conf/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      # - /docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=yourpass"
      - "MYSQL_DATABASE=mydb"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
  
  redis:
    image: redis:7.0-rc3
    volumes:
      - ./datadir/redis:/data #挂到宿主机
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/logs
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "
    ports:
      - 6379:6379
